import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const packageJson = JSON.parse(readFileSync("package.json", "utf8"));
const buildDate = new Date().toISOString();
const buildNumber = process.env.SYNC_TODOIST_BUILD_NUMBER ?? buildDate.replace(/[-:TZ.]/g, "").slice(0, 12);

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  define: {
    SYNC_TODOIST_VERSION: JSON.stringify(packageJson.version),
    SYNC_TODOIST_BUILD_DATE: JSON.stringify(buildDate),
    SYNC_TODOIST_BUILD_NUMBER: JSON.stringify(buildNumber),
  },
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
