/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TodoistSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var TodoistSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.projects = [];
    this.projectsLoaded = false;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Todoist API token").setDesc("Your todoist API token. Find it in todoist settings \u2192 integrations \u2192 developer.").addText((text) => {
      text.setPlaceholder("Enter your API token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
        this.projectsLoaded = false;
        this.projects = [];
      });
      text.inputEl.type = "password";
      text.inputEl.addClass("syncist-api-token-input");
    }).addButton((button) => {
      button.setButtonText("Verify").onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Verifying...");
        try {
          this.plugin.todoistService.initialize(this.plugin.settings.apiToken);
          const isValid = await this.plugin.todoistService.verifyToken();
          if (isValid) {
            new import_obsidian.Notice("API token is valid!");
            await this.loadProjects();
            this.display();
          } else {
            new import_obsidian.Notice("API token is invalid. Please check and try again.");
          }
        } catch (error) {
          new import_obsidian.Notice("Failed to verify token. Please check your internet connection.");
          console.warn("Token verification error:", error);
        } finally {
          button.setDisabled(false);
          button.setButtonText("Verify");
        }
      });
    });
    new import_obsidian.Setting(containerEl).setName("Sync tag").setDesc("Tag used to identify tasks for syncing. Include the # symbol.").addText(
      (text) => text.setPlaceholder("#todoist").setValue(this.plugin.settings.syncTag).onChange(async (value) => {
        if (value && !value.startsWith("#")) {
          value = "#" + value;
        }
        this.plugin.settings.syncTag = value || "#todoist";
        await this.plugin.saveSettings();
      })
    );
    if (this.plugin.settings.apiToken && !this.projectsLoaded) {
      void this.loadProjects().then(() => this.display());
    }
    const projectSetting = new import_obsidian.Setting(containerEl).setName("Default project").setDesc("Default todoist project for new tasks. Leave empty to use inbox.");
    if (this.projects.length > 0) {
      projectSetting.addDropdown((dropdown) => {
        dropdown.addOption("", "Inbox (default)");
        for (const project of this.projects) {
          dropdown.addOption(project.id, project.name);
        }
        dropdown.setValue(this.plugin.settings.defaultProjectId);
        dropdown.onChange(async (value) => {
          this.plugin.settings.defaultProjectId = value;
          await this.plugin.saveSettings();
        });
      });
    } else {
      projectSetting.addText((text) => {
        text.setPlaceholder("Verify API token to load projects").setValue(this.plugin.settings.defaultProjectId).setDisabled(true);
      });
    }
    new import_obsidian.Setting(containerEl).setName("Sync interval").setDesc("How often to sync with todoist (in minutes). Set to 0 to disable auto sync.").addText(
      (text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.syncIntervalMinutes)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.syncIntervalMinutes = num;
          await this.plugin.saveSettings();
          this.plugin.restartSyncInterval();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Conflict resolution").setDesc("How to handle conflicts when both sides have changes.").addDropdown((dropdown) => {
      dropdown.addOption("todoist-wins", "Todoist wins").addOption("obsidian-wins", "Local wins").addOption("ask-user", "Ask me each time").setValue(this.plugin.settings.conflictResolution).onChange(async (value) => {
        this.plugin.settings.conflictResolution = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Manual actions").setHeading();
    new import_obsidian.Setting(containerEl).setName("Sync now").setDesc("Manually trigger a sync.").addButton((button) => {
      button.setButtonText("Sync now").setCta().onClick(async () => {
        if (!this.plugin.settings.apiToken) {
          new import_obsidian.Notice("Please configure your API token first.");
          return;
        }
        button.setDisabled(true);
        button.setButtonText("Syncing...");
        try {
          const result = await this.plugin.syncNow();
          const message = `Sync complete: ${result.created} created, ${result.updated} updated, ${result.completed} completed`;
          new import_obsidian.Notice(message);
          if (result.errors.length > 0) {
            console.warn("Sync errors:", result.errors);
            new import_obsidian.Notice(`Sync had ${result.errors.length} error(s). Check console for details.`);
          }
          this.display();
        } catch (error) {
          new import_obsidian.Notice("Sync failed. Check console for details.");
          console.warn("Sync error:", error);
        } finally {
          button.setDisabled(false);
          button.setButtonText("Sync now");
        }
      });
    });
    new import_obsidian.Setting(containerEl).setName("Status").setHeading();
    const statusEl = containerEl.createDiv({ cls: "todoist-sync-status" });
    this.updateStatusDisplay(statusEl);
  }
  /**
   * Load projects from Todoist
   */
  async loadProjects() {
    if (!this.plugin.settings.apiToken) {
      return;
    }
    try {
      this.plugin.todoistService.initialize(this.plugin.settings.apiToken);
      this.projects = await this.plugin.todoistService.getProjects();
      this.projectsLoaded = true;
    } catch (error) {
      console.warn("Failed to load projects:", error);
      this.projects = [];
    }
  }
  /**
   * Update the status display
   */
  updateStatusDisplay(containerEl) {
    containerEl.empty();
    const syncState = this.plugin.getSyncState();
    const taskCount = Object.keys(syncState.tasks).length;
    const statusText = containerEl.createEl("p");
    statusText.textContent = `Synced tasks: ${taskCount}`;
    if (syncState.lastFullSync > 0) {
      const lastSync = new Date(syncState.lastFullSync);
      const lastSyncText = containerEl.createEl("p");
      lastSyncText.textContent = `Last sync: ${lastSync.toLocaleString()}`;
    } else {
      const lastSyncText = containerEl.createEl("p");
      lastSyncText.textContent = "Last sync: never";
    }
    const apiStatus = containerEl.createEl("p");
    apiStatus.textContent = `API status: ${this.plugin.todoistService.isInitialized() ? "Connected" : "Not connected"}`;
  }
};

// src/todoist-service.ts
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  apiToken: "",
  syncTag: "#todoist",
  defaultProjectId: "",
  syncIntervalMinutes: 5,
  conflictResolution: "todoist-wins"
};
function normalizeTask(raw) {
  var _a, _b, _c, _d;
  return {
    id: raw.id,
    content: raw.content,
    description: raw.description,
    projectId: raw.project_id,
    parentId: raw.parent_id,
    priority: raw.priority,
    due: raw.due,
    labels: (_a = raw.labels) != null ? _a : [],
    isCompleted: (_b = raw.checked) != null ? _b : raw.completed_at != null,
    createdAt: (_c = raw.added_at) != null ? _c : "",
    completedAt: (_d = raw.completed_at) != null ? _d : null,
    url: `https://todoist.com/app/task/${raw.id}`
  };
}
var DEFAULT_SYNC_STATE = {
  tasks: {},
  lastFullSync: 0
};

// src/todoist-service.ts
var API_BASE = "https://api.todoist.com/api/v1";
var TodoistService = class {
  constructor() {
    this.apiToken = null;
    this.projectCache = /* @__PURE__ */ new Map();
    this.reverseProjectCache = /* @__PURE__ */ new Map();
    this.inboxProjectId = null;
  }
  initialize(apiToken) {
    if (!apiToken) {
      this.apiToken = null;
      return;
    }
    this.apiToken = apiToken;
  }
  isInitialized() {
    return this.apiToken !== null;
  }
  headers() {
    return { "Authorization": `Bearer ${this.apiToken}` };
  }
  async verifyToken() {
    if (!this.apiToken)
      return false;
    try {
      await (0, import_obsidian2.requestUrl)({ url: `${API_BASE}/projects?limit=1`, headers: this.headers() });
      return true;
    } catch (error) {
      console.error("Todoist token verification failed:", error);
      return false;
    }
  }
  async getProjects() {
    var _a, _b;
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      const allProjects = [];
      let cursor = null;
      do {
        const params = new URLSearchParams({ limit: "200" });
        if (cursor)
          params.set("cursor", cursor);
        const resp = await (0, import_obsidian2.requestUrl)({
          url: `${API_BASE}/projects?${params.toString()}`,
          headers: this.headers()
        });
        const data = resp.json;
        allProjects.push(...(_a = data.results) != null ? _a : []);
        cursor = (_b = data.next_cursor) != null ? _b : null;
      } while (cursor);
      this.projectCache.clear();
      this.reverseProjectCache.clear();
      this.inboxProjectId = null;
      return allProjects.map((p) => {
        var _a2;
        this.projectCache.set(p.id, p.name);
        this.reverseProjectCache.set(p.name.toLowerCase(), p.id);
        if (p.inbox_project)
          this.inboxProjectId = p.id;
        return { id: p.id, name: p.name, isInbox: (_a2 = p.inbox_project) != null ? _a2 : false };
      });
    } catch (error) {
      console.error("Failed to get projects:", error);
      throw error;
    }
  }
  getProjectCache() {
    const cache = {};
    for (const [id, name] of this.projectCache) {
      cache[id] = name;
    }
    return cache;
  }
  getProjectName(projectId) {
    return this.projectCache.get(projectId);
  }
  getProjectIdByName(name) {
    return this.reverseProjectCache.get(name.toLowerCase());
  }
  isInboxProject(projectId) {
    return this.inboxProjectId === projectId;
  }
  async ensureProjectCache() {
    if (this.projectCache.size === 0) {
      await this.getProjects();
    }
  }
  async getTasks(projectId) {
    var _a, _b;
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      const allTasks = [];
      let cursor = null;
      do {
        const params = new URLSearchParams({ limit: "200" });
        if (projectId)
          params.set("project_id", projectId);
        if (cursor)
          params.set("cursor", cursor);
        const resp = await (0, import_obsidian2.requestUrl)({
          url: `${API_BASE}/tasks?${params.toString()}`,
          headers: this.headers()
        });
        const data = resp.json;
        for (const raw of (_a = data.results) != null ? _a : []) {
          allTasks.push(normalizeTask(raw));
        }
        cursor = (_b = data.next_cursor) != null ? _b : null;
      } while (cursor);
      console.debug(`Fetched ${allTasks.length} tasks from Todoist`);
      return allTasks;
    } catch (error) {
      console.error("Failed to get tasks:", error);
      throw error;
    }
  }
  async getSubtasks(parentId) {
    const allTasks = await this.getTasks();
    return allTasks.filter((t) => t.parentId === parentId);
  }
  async getTask(taskId) {
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      const resp = await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/tasks/${taskId}`,
        headers: this.headers()
      });
      return normalizeTask(resp.json);
    } catch (error) {
      if (error && typeof error === "object" && "status" in error && error.status === 404) {
        return null;
      }
      console.error("Failed to get task:", error);
      throw error;
    }
  }
  async createTask(content, options) {
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      const body = { content };
      if (options == null ? void 0 : options.projectId)
        body.project_id = options.projectId;
      if (options == null ? void 0 : options.parentId)
        body.parent_id = options.parentId;
      if (options == null ? void 0 : options.priority)
        body.priority = options.priority;
      if (options == null ? void 0 : options.dueDate)
        body.due_date = options.dueDate;
      if (options == null ? void 0 : options.labels)
        body.labels = options.labels;
      if (options == null ? void 0 : options.description)
        body.description = options.description;
      const resp = await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/tasks`,
        method: "POST",
        headers: { ...this.headers(), "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
      console.debug("Created Todoist task:", content);
      return normalizeTask(resp.json);
    } catch (error) {
      console.error("Failed to create task:", error);
      throw error;
    }
  }
  async updateTask(taskId, updates) {
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      const body = {};
      if (updates.content !== void 0)
        body.content = updates.content;
      if (updates.priority !== void 0)
        body.priority = updates.priority;
      if (updates.dueString !== void 0)
        body.due_string = updates.dueString;
      if (updates.labels !== void 0)
        body.labels = updates.labels;
      if (updates.description !== void 0)
        body.description = updates.description;
      const resp = await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/tasks/${taskId}`,
        method: "POST",
        headers: { ...this.headers(), "Content-Type": "application/json" },
        body: JSON.stringify(body)
      });
      console.debug("Updated Todoist task:", taskId);
      return normalizeTask(resp.json);
    } catch (error) {
      console.error("Failed to update task:", error);
      throw error;
    }
  }
  async completeTask(taskId) {
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/tasks/${taskId}/close`,
        method: "POST",
        headers: this.headers()
      });
      console.debug("Completed Todoist task:", taskId);
      return true;
    } catch (error) {
      console.error("Failed to complete task:", error);
      throw error;
    }
  }
  async reopenTask(taskId) {
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/tasks/${taskId}/reopen`,
        method: "POST",
        headers: this.headers()
      });
      console.debug("Reopened Todoist task:", taskId);
      return true;
    } catch (error) {
      console.error("Failed to reopen task:", error);
      throw error;
    }
  }
  async deleteTask(taskId) {
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    try {
      await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/tasks/${taskId}`,
        method: "DELETE",
        headers: this.headers()
      });
      console.debug("Deleted Todoist task:", taskId);
      return true;
    } catch (error) {
      console.error("Failed to delete task:", error);
      throw error;
    }
  }
  async getFilteredTasks(filter) {
    var _a, _b, _c, _d;
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    const allTasks = [];
    let cursor = null;
    do {
      const params = new URLSearchParams({ query: filter, limit: "200" });
      if (cursor)
        params.set("cursor", cursor);
      const resp = await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/tasks/filter?${params.toString()}`,
        headers: this.headers(),
        throw: false
      });
      if (resp.status === 400) {
        const body = resp.json;
        const detail = (_a = body == null ? void 0 : body.error) != null ? _a : "invalid filter expression";
        throw new Error(`Invalid filter: ${detail}`);
      }
      if (resp.status !== 200) {
        throw new Error(`Request failed, status ${resp.status}`);
      }
      const data = resp.json;
      const rawItems = (_c = (_b = data.items) != null ? _b : data.results) != null ? _c : [];
      for (const raw of rawItems) {
        allTasks.push(normalizeTask(raw));
      }
      cursor = (_d = data.next_cursor) != null ? _d : null;
    } while (cursor);
    return allTasks;
  }
  async getCompletedTasks(options) {
    var _a, _b, _c, _d, _e;
    if (!this.apiToken)
      throw new Error("Todoist API not initialized");
    const endpoint = options.by === "due_date" ? "tasks/completed/by_due_date" : "tasks/completed/by_completion_date";
    const allTasks = [];
    let cursor = null;
    do {
      const params = new URLSearchParams({
        filter_query: options.filterQuery,
        since: options.since.toISOString(),
        until: options.until.toISOString(),
        limit: "200"
      });
      if (cursor)
        params.set("cursor", cursor);
      const resp = await (0, import_obsidian2.requestUrl)({
        url: `${API_BASE}/${endpoint}?${params.toString()}`,
        headers: this.headers(),
        throw: false
      });
      if (resp.status === 400) {
        const body = resp.json;
        const detail = (_a = body == null ? void 0 : body.error) != null ? _a : "invalid completed task query";
        throw new Error(`Invalid completed task query: ${detail}`);
      }
      if (resp.status === 403) {
        throw new Error("Completed task archive unavailable for this Todoist account");
      }
      if (resp.status !== 200) {
        throw new Error(`Completed task request failed, status ${resp.status}`);
      }
      const data = resp.json;
      const rawItems = (_c = (_b = data.items) != null ? _b : data.results) != null ? _c : [];
      for (const raw of rawItems) {
        allTasks.push(normalizeTask({ ...raw, checked: (_d = raw.checked) != null ? _d : true }));
      }
      cursor = (_e = data.next_cursor) != null ? _e : null;
    } while (cursor);
    return allTasks;
  }
  static fromTodoistPriority(priority) {
    return priority;
  }
  static formatDueDate(date) {
    return date.toISOString().split("T")[0];
  }
  static parseDueDate(task) {
    if (!task.due)
      return null;
    return task.due.date;
  }
};

// src/sync-engine.ts
var import_obsidian3 = require("obsidian");

// src/task-parser.ts
var PATTERNS = {
  // Matches markdown task: - [ ] or - [x] or * [ ] etc.
  task: /^(\s*)[-*]\s+\[([ xX])\]\s+(.*)$/,
  // Matches Todoist ID comment: <!-- todoist-id:abc123 --> (v1 IDs are alphanumeric)
  todoistId: /<!--\s*todoist-id:\s*([\w]+)\s*-->/,
  // Matches hashtags: #tag (but not #project/ prefixed)
  hashtag: /#([a-zA-Z0-9_-]+)/g,
  // Tasks plugin emoji patterns
  dueDate: /📅\s*(\d{4}-\d{2}-\d{2})/,
  scheduledDate: /⏳\s*(\d{4}-\d{2}-\d{2})/,
  startDate: /🛫\s*(\d{4}-\d{2}-\d{2})/,
  doneDate: /✅\s*(\d{4}-\d{2}-\d{2})/,
  urgentPriority: /🔺/,
  highPriority: /⏫/,
  mediumPriority: /🔼/,
  lowPriority: /🔽/,
  // Alternative text-based due date: due:YYYY-MM-DD
  textDueDate: /due:(\d{4}-\d{2}-\d{2})/i,
  // Project metadata: 📁 ProjectName
  project: new RegExp("\u{1F4C1}\\s*([^\\s#\u{1F4C5}\u{1F53A}\u23EB\u{1F53C}\u{1F53D}<]+)", "u")
};
function getIndentLevel(line) {
  var _a, _b;
  const leading = (_b = (_a = line.match(/^(\s*)/)) == null ? void 0 : _a[1]) != null ? _b : "";
  let level = 0;
  let i = 0;
  while (i < leading.length) {
    if (leading[i] === "	") {
      level++;
      i++;
    } else if (leading[i] === " ") {
      let spaces = 0;
      while (i < leading.length && leading[i] === " ") {
        spaces++;
        i++;
      }
      level += Math.floor(spaces / 2);
    } else {
      i++;
    }
  }
  return level;
}
function parseTaskLine(line, lineNumber, filePath, syncTag, lastModified, requireSyncTag = true) {
  const match = line.match(PATTERNS.task);
  if (!match)
    return null;
  const [, , checkbox, taskContent] = match;
  const isCompleted = checkbox.toLowerCase() === "x";
  const syncTagPattern = new RegExp(escapeRegex(syncTag), "i");
  const hasSyncTag = syncTagPattern.test(taskContent);
  if (requireSyncTag && !hasSyncTag) {
    return null;
  }
  const todoistIdMatch = taskContent.match(PATTERNS.todoistId);
  const todoistId = todoistIdMatch ? todoistIdMatch[1] : null;
  const dueDate = extractDueDate(taskContent);
  const priority = extractPriority(taskContent);
  const labels = extractLabels(taskContent, syncTag);
  const content = cleanTaskContent(taskContent, syncTag);
  const indentLevel = getIndentLevel(line);
  const projectName = extractProjectName(taskContent);
  return {
    originalLine: line,
    lineNumber,
    filePath,
    content,
    isCompleted,
    todoistId,
    parentId: null,
    indentLevel,
    dueDate,
    priority,
    labels,
    description: "",
    projectId: null,
    projectName,
    lastModified
  };
}
function extractProjectName(content) {
  const match = content.match(PATTERNS.project);
  return match ? match[1] : null;
}
function extractDueDate(content) {
  const emojiMatch = content.match(PATTERNS.dueDate);
  if (emojiMatch)
    return emojiMatch[1];
  const scheduledMatch = content.match(PATTERNS.scheduledDate);
  if (scheduledMatch)
    return scheduledMatch[1];
  const textMatch = content.match(PATTERNS.textDueDate);
  if (textMatch)
    return textMatch[1];
  return null;
}
function extractPriority(content) {
  if (PATTERNS.urgentPriority.test(content)) {
    return 4 /* HIGH */;
  }
  if (PATTERNS.highPriority.test(content)) {
    return 3 /* MEDIUM */;
  }
  if (PATTERNS.mediumPriority.test(content)) {
    return 2 /* LOW */;
  }
  if (PATTERNS.lowPriority.test(content)) {
    return 1 /* NONE */;
  }
  return 1 /* NONE */;
}
function extractLabels(content, syncTag) {
  const labels = [];
  const syncTagName = syncTag.replace(/^#/, "").toLowerCase();
  let match;
  while ((match = PATTERNS.hashtag.exec(content)) !== null) {
    const tag = match[1];
    if (tag.toLowerCase() !== syncTagName) {
      labels.push(tag);
    }
  }
  PATTERNS.hashtag.lastIndex = 0;
  return labels;
}
function cleanTaskContent(content, syncTag) {
  let cleaned = content;
  cleaned = cleaned.replace(/<!--\s*todoist-id:\s*[\w]+\s*-->/g, "");
  const syncTagPattern = new RegExp(escapeRegex(syncTag), "gi");
  cleaned = cleaned.replace(syncTagPattern, "");
  cleaned = cleaned.replace(PATTERNS.dueDate, "");
  cleaned = cleaned.replace(PATTERNS.scheduledDate, "");
  cleaned = cleaned.replace(PATTERNS.startDate, "");
  cleaned = cleaned.replace(PATTERNS.doneDate, "");
  cleaned = cleaned.replace(PATTERNS.urgentPriority, "");
  cleaned = cleaned.replace(PATTERNS.highPriority, "");
  cleaned = cleaned.replace(PATTERNS.mediumPriority, "");
  cleaned = cleaned.replace(PATTERNS.lowPriority, "");
  cleaned = cleaned.replace(PATTERNS.textDueDate, "");
  cleaned = cleaned.replace(PATTERNS.project, "");
  cleaned = cleaned.replace(/#[a-zA-Z0-9_-]+/g, "");
  cleaned = cleaned.replace(/\s+/g, " ").trim();
  return cleaned;
}
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function buildTaskLine(task, syncTag) {
  const indent = "	".repeat(task.indentLevel);
  const checkbox = task.isCompleted ? "[x]" : "[ ]";
  let line = `${indent}- ${checkbox} ${task.content}`;
  if (task.indentLevel === 0) {
    line += ` ${syncTag}`;
  }
  for (const label of task.labels) {
    line += ` #${label}`;
  }
  if (task.projectName) {
    line += ` \u{1F4C1} ${task.projectName}`;
  }
  if (task.priority === 4 /* HIGH */) {
    line += " \u{1F53A}";
  } else if (task.priority === 3 /* MEDIUM */) {
    line += " \u23EB";
  } else if (task.priority === 2 /* LOW */) {
    line += " \u{1F53C}";
  }
  if (task.dueDate) {
    line += ` \u{1F4C5} ${task.dueDate}`;
  }
  if (task.todoistId) {
    line += ` <!-- todoist-id:${task.todoistId} -->`;
  }
  return line;
}
function addTodoistIdToLine(line, todoistId) {
  var _a, _b;
  const leadingWhitespace = (_b = (_a = line.match(/^(\s*)/)) == null ? void 0 : _a[1]) != null ? _b : "";
  const stripped = line.replace(/<!--\s*todoist-id:\s*[\w]+\s*-->/g, "").trimEnd();
  const withoutLeading = stripped.trimStart();
  const updated = `${leadingWhitespace}${withoutLeading} <!-- todoist-id:${todoistId} -->`;
  return updated;
}
function updateTaskCompletion(line, isCompleted) {
  if (isCompleted) {
    return line.replace(/\[\s\]/, "[x]");
  } else {
    return line.replace(/\[[xX]\]/, "[ ]");
  }
}
function parseTasksFromContent(content, filePath, syncTag, lastModified) {
  const lines = content.split("\n");
  const tasks = [];
  const parentStack = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const lineIndent = getIndentLevel(line);
    let task = parseTaskLine(line, i, filePath, syncTag, lastModified, true);
    if (task) {
      while (parentStack.length > 0 && parentStack[parentStack.length - 1].indentLevel >= lineIndent) {
        parentStack.pop();
      }
      if (parentStack.length > 0) {
        const parent = parentStack[parentStack.length - 1].task;
        task.parentId = parent.todoistId;
      }
      const description = extractDescription(lines, i);
      task.description = description;
      tasks.push(task);
      parentStack.push({ indentLevel: lineIndent, task });
      continue;
    }
    if (parentStack.length > 0) {
      while (parentStack.length > 0 && parentStack[parentStack.length - 1].indentLevel >= lineIndent) {
        parentStack.pop();
      }
      if (parentStack.length > 0) {
        task = parseTaskLine(line, i, filePath, syncTag, lastModified, false);
        if (task) {
          const parent = parentStack[parentStack.length - 1].task;
          task.parentId = parent.todoistId;
          const description = extractDescription(lines, i);
          task.description = description;
          tasks.push(task);
          parentStack.push({ indentLevel: lineIndent, task });
          continue;
        }
      }
    }
    if (line.trim() === "" || line.trim() && lineIndent === 0 && !PATTERNS.task.test(line)) {
      if (lineIndent === 0 && line.trim() !== "") {
        parentStack.length = 0;
      }
    }
  }
  return tasks;
}
function extractDescription(lines, taskIndex) {
  var _a, _b, _c, _d;
  const taskLine = lines[taskIndex];
  const taskIndent = (_b = (_a = taskLine.match(/^(\s*)/)) == null ? void 0 : _a[1].length) != null ? _b : 0;
  const descriptionLines = [];
  for (let i = taskIndex + 1; i < lines.length; i++) {
    const line = lines[i];
    const lineIndent = (_d = (_c = line.match(/^(\s*)/)) == null ? void 0 : _c[1].length) != null ? _d : 0;
    if (line.trim() && lineIndent <= taskIndent) {
      break;
    }
    if (PATTERNS.task.test(line)) {
      break;
    }
    if (line.trim()) {
      descriptionLines.push(line.trim());
    }
  }
  return descriptionLines.join("\n");
}
function generateContentHash(task) {
  var _a;
  const sortedLabels = [...task.labels].sort().join(",");
  const data = `${task.content}|${task.isCompleted}|${(_a = task.dueDate) != null ? _a : ""}|${task.priority}|${sortedLabels}`;
  let hash = 0;
  for (let i = 0; i < data.length; i++) {
    const char = data.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash;
  }
  return hash.toString(16);
}

// src/sync-engine.ts
var SyncEngine = class {
  constructor(app, todoistService, settings, syncState) {
    this.isSyncing = false;
    this.pendingConflicts = [];
    this.app = app;
    this.todoistService = todoistService;
    this.settings = settings;
    this.syncState = syncState;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  updateSyncState(syncState) {
    this.syncState = syncState;
  }
  /**
   * Resolve the display project name for a Todoist task.
   * Returns null when the task is in the configured default project (or inbox
   * when no default is set) so that 📁 is not written to the task line.
   */
  resolveProjectName(projectId) {
    var _a;
    if (this.settings.defaultProjectId) {
      if (projectId === this.settings.defaultProjectId)
        return null;
    } else {
      if (this.todoistService.isInboxProject(projectId))
        return null;
    }
    return (_a = this.todoistService.getProjectName(projectId)) != null ? _a : null;
  }
  getSyncState() {
    return this.syncState;
  }
  isCurrentlySyncing() {
    return this.isSyncing;
  }
  /**
   * Perform a full bidirectional sync
   */
  async performSync() {
    if (this.isSyncing) {
      console.debug("Todoist Sync: Already in progress, skipping...");
      return { created: 0, updated: 0, completed: 0, conflicts: 0, errors: ["Sync already in progress"] };
    }
    if (!this.todoistService.isInitialized()) {
      console.debug("Todoist Sync: API not configured");
      return { created: 0, updated: 0, completed: 0, conflicts: 0, errors: ["Todoist API not configured"] };
    }
    this.isSyncing = true;
    const result = { created: 0, updated: 0, completed: 0, conflicts: 0, errors: [] };
    try {
      console.debug("Todoist Sync: Starting sync...");
      await this.todoistService.ensureProjectCache();
      console.debug("Todoist Sync: Fetching Todoist tasks...");
      let todoistTasks = [];
      try {
        todoistTasks = await this.todoistService.getTasks();
        console.debug(`Todoist Sync: Found ${todoistTasks.length} tasks in Todoist`);
      } catch (error) {
        console.error("Todoist Sync: Failed to fetch Todoist tasks:", error);
        result.errors.push(`Failed to fetch Todoist tasks: ${error}`);
        this.isSyncing = false;
        return result;
      }
      const todoistTaskMap = /* @__PURE__ */ new Map();
      for (const task of todoistTasks) {
        todoistTaskMap.set(task.id, task);
      }
      console.debug("Todoist Sync: Scanning vault for tasks...");
      const obsidianTasks = await this.getAllObsidianTasks();
      console.debug(`Todoist Sync: Found ${obsidianTasks.length} tasks with ${this.settings.syncTag} tag`);
      const syncedObsidianTasks = /* @__PURE__ */ new Map();
      const newObsidianTasks = [];
      for (const task of obsidianTasks) {
        if (task.todoistId) {
          syncedObsidianTasks.set(task.todoistId, task);
        } else {
          newObsidianTasks.push(task);
        }
      }
      console.debug(`Todoist Sync: ${newObsidianTasks.length} new tasks to create, ${syncedObsidianTasks.size} existing tasks to sync`);
      const sortedNewTasks = [...newObsidianTasks].sort((a, b) => a.indentLevel - b.indentLevel);
      const createdTaskMap = /* @__PURE__ */ new Map();
      const newlyCreatedIds = /* @__PURE__ */ new Set();
      for (let i = 0; i < sortedNewTasks.length; i++) {
        await new Promise((resolve) => window.setTimeout(resolve, 0));
        const task = sortedNewTasks[i];
        try {
          let parentId = task.parentId;
          if (!parentId && task.indentLevel > 0) {
            parentId = this.findParentTodoistId(task, obsidianTasks, createdTaskMap);
          }
          console.debug(`Todoist Sync: Creating task ${i + 1}/${sortedNewTasks.length}: "${task.content}" (parent: ${parentId != null ? parentId : "none"})`);
          const todoistTask = await this.createTodoistTaskWithParent(task, parentId);
          createdTaskMap.set(`${task.filePath}:${task.lineNumber}`, todoistTask.id);
          newlyCreatedIds.add(todoistTask.id);
          result.created++;
        } catch (error) {
          result.errors.push(`Failed to create task: ${task.content} - ${error}`);
          console.error("Todoist Sync: Failed to create task:", error);
        }
      }
      const syncEntries = [...syncedObsidianTasks.entries()];
      for (let i = 0; i < syncEntries.length; i++) {
        await new Promise((resolve) => window.setTimeout(resolve, 0));
        const [todoistId, obsidianTask] = syncEntries[i];
        const todoistTask = todoistTaskMap.get(todoistId);
        if (!todoistTask) {
          try {
            console.debug(`Todoist Sync: Task ${todoistId} not found in Todoist, marking completed`);
            await this.markObsidianTaskCompleted(obsidianTask);
            result.completed++;
            delete this.syncState.tasks[todoistId];
          } catch (error) {
            result.errors.push(`Failed to mark task completed: ${obsidianTask.content}`);
            console.error("Todoist Sync: Failed to mark task completed:", error);
          }
          continue;
        }
        try {
          const syncResult = await this.syncExistingTask(obsidianTask, todoistTask);
          if (syncResult === "updated")
            result.updated++;
          if (syncResult === "conflict")
            result.conflicts++;
          if (syncResult === "completed")
            result.completed++;
        } catch (error) {
          result.errors.push(`Failed to sync task: ${obsidianTask.content} - ${error}`);
          console.error("Todoist Sync: Failed to sync existing task:", error);
        }
        if ((i + 1) % 25 === 0 || i === syncEntries.length - 1) {
          console.debug(`Todoist Sync: Synced ${i + 1}/${syncEntries.length} existing tasks`);
        }
      }
      for (const todoistId of Object.keys(this.syncState.tasks)) {
        if (!syncedObsidianTasks.has(todoistId) && !newlyCreatedIds.has(todoistId)) {
          console.debug(`Todoist Sync: Removing stale sync state entry for ${todoistId}`);
          delete this.syncState.tasks[todoistId];
        }
      }
      this.syncState.lastFullSync = Date.now();
      console.debug("Todoist Sync: Completed!", result);
    } catch (error) {
      result.errors.push(`Sync failed: ${error}`);
      console.error("Todoist Sync: Sync failed with error:", error);
    } finally {
      this.isSyncing = false;
    }
    return result;
  }
  /**
   * Find the Todoist parent ID for a subtask by walking up the indent hierarchy.
   */
  findParentTodoistId(task, allTasks, createdTaskMap) {
    var _a;
    const samefile = allTasks.filter((t) => t.filePath === task.filePath && t.lineNumber < task.lineNumber);
    for (let i = samefile.length - 1; i >= 0; i--) {
      const candidate = samefile[i];
      if (candidate.indentLevel < task.indentLevel) {
        if (candidate.todoistId)
          return candidate.todoistId;
        const key = `${candidate.filePath}:${candidate.lineNumber}`;
        return (_a = createdTaskMap.get(key)) != null ? _a : null;
      }
    }
    return null;
  }
  /**
   * Get all tasks from all markdown files in the vault
   */
  async getAllObsidianTasks() {
    const tasks = [];
    const files = this.app.vault.getMarkdownFiles();
    console.debug(`Todoist Sync: Vault has ${files.length} markdown files`);
    for (let i = 0; i < files.length; i++) {
      await new Promise((resolve) => window.setTimeout(resolve, 0));
      const file = files[i];
      try {
        const content = await this.app.vault.cachedRead(file);
        const fileTasks = parseTasksFromContent(
          content,
          file.path,
          this.settings.syncTag,
          file.stat.mtime
        );
        tasks.push(...fileTasks);
      } catch (error) {
        console.error(`Failed to read file ${file.path}:`, error);
      }
    }
    console.debug(`Todoist Sync: Scan complete \u2014 ${files.length} files, ${tasks.length} tasks found`);
    return tasks;
  }
  /**
   * Create a Todoist task from an Obsidian task, with optional parentId
   */
  async createTodoistTaskWithParent(task, parentId) {
    var _a;
    let projectId = this.settings.defaultProjectId || void 0;
    if (task.projectName) {
      const resolvedId = this.todoistService.getProjectIdByName(task.projectName);
      if (resolvedId)
        projectId = resolvedId;
    }
    const todoistTask = await this.todoistService.createTask(task.content, {
      projectId: parentId ? void 0 : projectId,
      // Subtasks inherit project from parent
      parentId: parentId != null ? parentId : void 0,
      priority: task.priority,
      dueDate: (_a = task.dueDate) != null ? _a : void 0,
      labels: task.labels,
      description: task.description
    });
    await this.updateObsidianTaskLine(task, (line) => addTodoistIdToLine(line, todoistTask.id));
    this.syncState.tasks[todoistTask.id] = {
      todoistId: todoistTask.id,
      parentId,
      filePath: task.filePath,
      lineNumber: task.lineNumber,
      contentHash: generateContentHash(task),
      lastSynced: Date.now(),
      obsidianCompleted: task.isCompleted,
      todoistCompleted: todoistTask.isCompleted,
      projectId: todoistTask.projectId
    };
    if (task.isCompleted) {
      await this.todoistService.completeTask(todoistTask.id);
    }
    return todoistTask;
  }
  /**
   * @deprecated Use createTodoistTaskWithParent instead
   */
  async createTodoistTask(task) {
    await this.createTodoistTaskWithParent(task, task.parentId);
  }
  /**
   * Sync an existing task between Obsidian and Todoist
   */
  async syncExistingTask(obsidianTask, todoistTask) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i;
    const obsidianCompleted = obsidianTask.isCompleted;
    const todoistCompleted = todoistTask.isCompleted;
    if (obsidianCompleted !== todoistCompleted) {
      if (obsidianCompleted && !todoistCompleted) {
        await this.todoistService.completeTask(todoistTask.id);
        this.updateSyncStateTask(todoistTask.id, obsidianTask, true, todoistTask);
        return "completed";
      } else if (!obsidianCompleted && todoistCompleted) {
        if (this.settings.conflictResolution === "todoist-wins") {
          await this.markObsidianTaskCompleted(obsidianTask);
          this.updateSyncStateTask(todoistTask.id, obsidianTask, true, todoistTask);
          return "completed";
        } else if (this.settings.conflictResolution === "obsidian-wins") {
          await this.todoistService.reopenTask(todoistTask.id);
          this.updateSyncStateTask(todoistTask.id, obsidianTask, false, todoistTask);
          return "updated";
        } else {
          await this.markObsidianTaskCompleted(obsidianTask);
          this.updateSyncStateTask(todoistTask.id, obsidianTask, true, todoistTask);
          return "conflict";
        }
      }
    }
    const todoistContent = todoistTask.content;
    const todoistPriority = TodoistService.fromTodoistPriority(todoistTask.priority);
    const todoistDueDate = TodoistService.parseDueDate(todoistTask);
    const contentDiffers = obsidianTask.content !== todoistContent;
    const priorityDiffers = obsidianTask.priority !== todoistPriority;
    const dueDateDiffers = obsidianTask.dueDate !== todoistDueDate;
    const todoistLabels = [...(_a = todoistTask.labels) != null ? _a : []].sort();
    const obsidianLabels = [...obsidianTask.labels].sort();
    const labelsDiffer = JSON.stringify(todoistLabels) !== JSON.stringify(obsidianLabels);
    const todoistProjectName = (_b = this.todoistService.getProjectName(todoistTask.projectId)) != null ? _b : null;
    const projectDiffers = todoistProjectName !== ((_c = obsidianTask.projectName) != null ? _c : null);
    const hasChanges = contentDiffers || priorityDiffers || dueDateDiffers || labelsDiffer || projectDiffers;
    if (!hasChanges) {
      this.updateSyncStateTask(todoistTask.id, obsidianTask, obsidianCompleted, todoistTask);
      return "unchanged";
    }
    const storedHash = (_e = (_d = this.syncState.tasks[todoistTask.id]) == null ? void 0 : _d.contentHash) != null ? _e : "";
    const currentObsidianHash = generateContentHash(obsidianTask);
    const todoistAsObsidian = {
      ...obsidianTask,
      content: todoistContent,
      priority: todoistPriority,
      dueDate: todoistDueDate,
      labels: (_f = todoistTask.labels) != null ? _f : [],
      isCompleted: todoistTask.isCompleted,
      parentId: (_g = todoistTask.parentId) != null ? _g : null,
      projectId: todoistTask.projectId
    };
    const currentTodoistHash = generateContentHash(todoistAsObsidian);
    const obsidianChanged = currentObsidianHash !== storedHash;
    const todoistChanged = currentTodoistHash !== storedHash;
    if (projectDiffers && !obsidianChanged && !todoistChanged) {
      await this.updateObsidianTaskFromTodoist(obsidianTask, todoistTask);
      this.updateSyncStateTask(todoistTask.id, obsidianTask, obsidianCompleted, todoistTask);
      return "updated";
    }
    if (obsidianChanged && !todoistChanged) {
      await this.todoistService.updateTask(todoistTask.id, {
        content: obsidianTask.content,
        priority: obsidianTask.priority,
        dueString: (_h = obsidianTask.dueDate) != null ? _h : void 0,
        labels: obsidianTask.labels
      });
      this.updateSyncStateTask(todoistTask.id, obsidianTask, obsidianCompleted, todoistTask);
      return "updated";
    }
    if (todoistChanged && !obsidianChanged) {
      await this.updateObsidianTaskFromTodoist(obsidianTask, todoistTask);
      this.updateSyncStateTask(todoistTask.id, obsidianTask, obsidianCompleted, todoistTask);
      return "updated";
    }
    if (this.settings.conflictResolution === "obsidian-wins") {
      await this.todoistService.updateTask(todoistTask.id, {
        content: obsidianTask.content,
        priority: obsidianTask.priority,
        dueString: (_i = obsidianTask.dueDate) != null ? _i : void 0,
        labels: obsidianTask.labels
      });
      this.updateSyncStateTask(todoistTask.id, obsidianTask, obsidianCompleted, todoistTask);
      return "updated";
    } else if (this.settings.conflictResolution === "todoist-wins") {
      await this.updateObsidianTaskFromTodoist(obsidianTask, todoistTask);
      this.updateSyncStateTask(todoistTask.id, obsidianTask, obsidianCompleted, todoistTask);
      return "updated";
    } else {
      this.pendingConflicts.push({
        todoistId: todoistTask.id,
        filePath: obsidianTask.filePath,
        lineNumber: obsidianTask.lineNumber,
        obsidianContent: obsidianTask.content,
        todoistContent,
        obsidianCompleted,
        todoistCompleted
      });
      return "conflict";
    }
  }
  /**
   * Update sync state for a task
   */
  updateSyncStateTask(todoistId, obsidianTask, completed, todoistTask) {
    var _a, _b, _c, _d;
    this.syncState.tasks[todoistId] = {
      todoistId,
      parentId: (_b = (_a = todoistTask == null ? void 0 : todoistTask.parentId) != null ? _a : obsidianTask.parentId) != null ? _b : null,
      filePath: obsidianTask.filePath,
      lineNumber: obsidianTask.lineNumber,
      contentHash: generateContentHash(obsidianTask),
      lastSynced: Date.now(),
      obsidianCompleted: completed,
      todoistCompleted: completed,
      projectId: (_d = (_c = todoistTask == null ? void 0 : todoistTask.projectId) != null ? _c : obsidianTask.projectId) != null ? _d : null
    };
  }
  /**
   * Update Obsidian task from Todoist data
   */
  async updateObsidianTaskFromTodoist(obsidianTask, todoistTask) {
    var _a;
    const projectName = this.resolveProjectName(todoistTask.projectId);
    const updatedTask = {
      ...obsidianTask,
      content: todoistTask.content,
      priority: TodoistService.fromTodoistPriority(todoistTask.priority),
      dueDate: TodoistService.parseDueDate(todoistTask),
      isCompleted: todoistTask.isCompleted,
      labels: (_a = todoistTask.labels) != null ? _a : [],
      projectName
    };
    const newLine = buildTaskLine(updatedTask, this.settings.syncTag);
    await this.replaceLineInFile(obsidianTask.filePath, obsidianTask.lineNumber, newLine);
  }
  /**
   * Mark an Obsidian task as completed
   */
  async markObsidianTaskCompleted(task) {
    await this.updateObsidianTaskLine(task, (line) => updateTaskCompletion(line, true));
  }
  /**
   * Update a specific line in the Obsidian task
   */
  async updateObsidianTaskLine(task, transform) {
    const file = this.app.vault.getAbstractFileByPath(task.filePath);
    if (!(file instanceof import_obsidian3.TFile)) {
      throw new Error(`File not found: ${task.filePath}`);
    }
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    if (task.lineNumber >= lines.length) {
      throw new Error(`Line number out of range: ${task.lineNumber}`);
    }
    lines[task.lineNumber] = transform(lines[task.lineNumber]);
    await this.app.vault.modify(file, lines.join("\n"));
  }
  /**
   * Replace a line in a file
   */
  async replaceLineInFile(filePath, lineNumber, newLine) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian3.TFile)) {
      throw new Error(`File not found: ${filePath}`);
    }
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    if (lineNumber >= lines.length) {
      throw new Error(`Line number out of range: ${lineNumber}`);
    }
    lines[lineNumber] = newLine;
    await this.app.vault.modify(file, lines.join("\n"));
  }
  /**
   * Import a Todoist task (and its subtasks) at the cursor position in a file.
   * Returns the number of lines inserted.
   */
  async importTaskAtCursor(task, subtasks, filePath, lineNumber) {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const projectName = this.resolveProjectName(task.projectId);
    const parentParsed = {
      originalLine: "",
      lineNumber,
      filePath,
      content: task.content,
      isCompleted: task.isCompleted,
      todoistId: task.id,
      parentId: (_a = task.parentId) != null ? _a : null,
      indentLevel: 0,
      dueDate: TodoistService.parseDueDate(task),
      priority: TodoistService.fromTodoistPriority(task.priority),
      labels: (_b = task.labels) != null ? _b : [],
      description: (_c = task.description) != null ? _c : "",
      projectId: task.projectId,
      projectName,
      lastModified: Date.now()
    };
    const lines = [buildTaskLine(parentParsed, this.settings.syncTag)];
    this.syncState.tasks[task.id] = {
      todoistId: task.id,
      parentId: (_d = task.parentId) != null ? _d : null,
      filePath,
      lineNumber,
      contentHash: generateContentHash(parentParsed),
      lastSynced: Date.now(),
      obsidianCompleted: task.isCompleted,
      todoistCompleted: task.isCompleted,
      projectId: task.projectId
    };
    for (let i = 0; i < subtasks.length; i++) {
      const sub = subtasks[i];
      const subParsed = {
        originalLine: "",
        lineNumber: lineNumber + 1 + i,
        filePath,
        content: sub.content,
        isCompleted: sub.isCompleted,
        todoistId: sub.id,
        parentId: (_e = sub.parentId) != null ? _e : task.id,
        indentLevel: 1,
        dueDate: TodoistService.parseDueDate(sub),
        priority: TodoistService.fromTodoistPriority(sub.priority),
        labels: (_f = sub.labels) != null ? _f : [],
        description: (_g = sub.description) != null ? _g : "",
        projectId: sub.projectId,
        projectName: null,
        lastModified: Date.now()
      };
      lines.push(buildTaskLine(subParsed, this.settings.syncTag));
      this.syncState.tasks[sub.id] = {
        todoistId: sub.id,
        parentId: (_h = sub.parentId) != null ? _h : task.id,
        filePath,
        lineNumber: lineNumber + 1 + i,
        contentHash: generateContentHash(subParsed),
        lastSynced: Date.now(),
        obsidianCompleted: sub.isCompleted,
        todoistCompleted: sub.isCompleted,
        projectId: sub.projectId
      };
    }
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!(file instanceof import_obsidian3.TFile)) {
      throw new Error(`File not found: ${filePath}`);
    }
    const fileContent = await this.app.vault.read(file);
    const fileLines = fileContent.split("\n");
    fileLines.splice(lineNumber, 0, ...lines);
    await this.app.vault.modify(file, fileLines.join("\n"));
    return lines.length;
  }
  /**
   * Create a Todoist task from the current editor line
   */
  async createTaskFromLine(filePath, lineNumber, lineContent) {
    var _a, _b;
    if (!this.todoistService.isInitialized()) {
      return { success: false, message: "Todoist API not configured. Please add your API key in settings." };
    }
    const taskMatch = lineContent.match(/^(\s*)[-*]\s+\[([ xX])\]\s+(.*)$/);
    let content;
    let isTask = false;
    let prefix = "";
    if (taskMatch) {
      isTask = true;
      prefix = taskMatch[1];
      content = taskMatch[3];
      const todoistIdMatch = content.match(/<!--\s*todoist-id:\s*([\w]+)\s*-->/);
      if (todoistIdMatch) {
        return { success: false, message: "Task is already synced with Todoist." };
      }
      const syncTagPattern = new RegExp(this.settings.syncTag.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i");
      if (!syncTagPattern.test(content)) {
        content = content.trim() + " " + this.settings.syncTag;
      }
    } else {
      const trimmed = lineContent.trim();
      if (!trimmed) {
        return { success: false, message: "Cannot create task from empty line." };
      }
      let cleanedContent = trimmed.replace(/^[-*+]\s+/, "").replace(/^\d+\.\s+/, "").trim();
      if (!cleanedContent) {
        return { success: false, message: "Cannot create task from empty bullet." };
      }
      content = cleanedContent + " " + this.settings.syncTag;
      prefix = (_b = (_a = lineContent.match(/^(\s*)/)) == null ? void 0 : _a[1]) != null ? _b : "";
    }
    const cleanContent = content.replace(new RegExp(this.settings.syncTag.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "gi"), "").replace(/#[a-zA-Z0-9_-]+/g, "").replace(/📅\s*\d{4}-\d{2}-\d{2}/g, "").replace(/🔺|⏫|🔼|🔽/g, "").replace(/📁\s*\S+/g, "").replace(/\s+/g, " ").trim();
    try {
      const todoistTask = await this.todoistService.createTask(cleanContent, {
        projectId: this.settings.defaultProjectId || void 0
      });
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (!(file instanceof import_obsidian3.TFile)) {
        return { success: false, message: "File not found." };
      }
      const fileContent = await this.app.vault.read(file);
      const lines = fileContent.split("\n");
      let newLine;
      if (isTask) {
        newLine = addTodoistIdToLine(lineContent, todoistTask.id);
        if (!new RegExp(this.settings.syncTag.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i").test(newLine)) {
          newLine = newLine.replace(/(\s*)<!--/, ` ${this.settings.syncTag}$1<!--`);
        }
      } else {
        newLine = `${prefix}- [ ] ${content} <!-- todoist-id:${todoistTask.id} -->`;
      }
      lines[lineNumber] = newLine;
      await this.app.vault.modify(file, lines.join("\n"));
      this.syncState.tasks[todoistTask.id] = {
        todoistId: todoistTask.id,
        parentId: null,
        filePath,
        lineNumber,
        contentHash: "",
        lastSynced: Date.now(),
        obsidianCompleted: false,
        todoistCompleted: false,
        projectId: todoistTask.projectId
      };
      return { success: true, message: `Created Todoist task: ${cleanContent}` };
    } catch (error) {
      console.error("Failed to create Todoist task:", error);
      return { success: false, message: `Failed to create task: ${error}` };
    }
  }
  getPendingConflicts() {
    return this.pendingConflicts;
  }
  clearPendingConflicts() {
    this.pendingConflicts = [];
  }
};

// src/import-modal.ts
var import_obsidian4 = require("obsidian");
var ImportTaskModal = class extends import_obsidian4.SuggestModal {
  constructor(app, todoistService, onSelect) {
    super(app);
    this.allTasks = [];
    this.loading = true;
    this.todoistService = todoistService;
    this.onSelect = onSelect;
    this.setPlaceholder("Search for a todoist task...");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "navigate" },
      { command: "\u21B5", purpose: "import task (with subtasks)" },
      { command: "esc", purpose: "cancel" }
    ]);
    void this.loadTasks();
  }
  async loadTasks() {
    try {
      await this.todoistService.ensureProjectCache();
      this.allTasks = await this.todoistService.getTasks();
      this.loading = false;
      this.inputEl.dispatchEvent(new Event("input"));
    } catch (error) {
      console.error("Failed to load tasks for import:", error);
      new import_obsidian4.Notice("Failed to load todoist tasks. Check your API token.");
      this.close();
    }
  }
  getSuggestions(query) {
    if (this.loading)
      return [];
    const topLevel = this.allTasks.filter((t) => !t.parentId);
    if (!query.trim()) {
      return topLevel.slice(0, 50);
    }
    const lower = query.toLowerCase();
    return topLevel.filter((task) => {
      var _a, _b, _c, _d, _e;
      const content = task.content.toLowerCase();
      const projectName = (_b = (_a = this.todoistService.getProjectName(task.projectId)) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
      const labels = task.labels.join(" ").toLowerCase();
      const dueStr = (_e = (_d = (_c = task.due) == null ? void 0 : _c.date) == null ? void 0 : _d.toLowerCase()) != null ? _e : "";
      return content.includes(lower) || projectName.includes(lower) || labels.includes(lower) || dueStr.includes(lower);
    }).slice(0, 50);
  }
  renderSuggestion(task, el) {
    var _a;
    const container = el.createDiv({ cls: "syncist-import-suggestion" });
    const priorityMap = { 4: "\u{1F53A}", 3: "\u23EB", 2: "\u{1F53C}" };
    const priorityEmoji = (_a = priorityMap[task.priority]) != null ? _a : "";
    const titleEl = container.createDiv({ cls: "syncist-import-title" });
    if (priorityEmoji) {
      titleEl.createSpan({ text: priorityEmoji + " ", cls: "syncist-import-priority" });
    }
    titleEl.createSpan({ text: task.content });
    const metaEl = container.createDiv({ cls: "syncist-import-meta" });
    const parts = [];
    const projectName = this.todoistService.getProjectName(task.projectId);
    if (projectName)
      parts.push(`\u{1F4C1} ${projectName}`);
    if (task.due)
      parts.push(`\u{1F4C5} ${task.due.date}`);
    if (task.labels.length)
      parts.push(task.labels.map((l) => `#${l}`).join(" "));
    const subtaskCount = this.allTasks.filter((t) => t.parentId === task.id).length;
    if (subtaskCount > 0)
      parts.push(`${subtaskCount} subtask${subtaskCount > 1 ? "s" : ""}`);
    if (parts.length > 0) {
      metaEl.createSpan({ text: parts.join("  \xB7  "), cls: "syncist-import-meta-text" });
    }
  }
  onChooseSuggestion(task) {
    const subtasks = this.allTasks.filter((t) => t.parentId === task.id);
    this.onSelect(task, subtasks);
  }
};

// src/query-renderer.ts
var import_obsidian5 = require("obsidian");
var DAY_MS = 24 * 60 * 60 * 1e3;
var MAX_COMPLETED_WINDOW_DAYS = {
  due_date: 42,
  completion_date: 93
};
function parseQueryConfig(source) {
  const lines = source.trim().split("\n");
  let filter = "";
  let includeCompleted = false;
  let completedBy = null;
  let completedSince = null;
  let completedUntil = null;
  let completedRange = null;
  for (const line of lines) {
    const match = line.match(/^\s*([a-z_]+)\s*:\s*(.+)$/i);
    if (!match) {
      continue;
    }
    const key = match[1].toLowerCase();
    const value = match[2].trim();
    if (key === "filter") {
      filter = value;
    } else if (key === "include_completed") {
      includeCompleted = ["true", "yes", "1", "on"].includes(value.toLowerCase());
    } else if (key === "completed_by") {
      if (value !== "due_date" && value !== "completion_date") {
        return { config: null, error: "Invalid completed_by. Use due_date or completion_date." };
      }
      completedBy = value;
    } else if (key === "completed_since") {
      completedSince = value;
    } else if (key === "completed_until") {
      completedUntil = value;
    } else if (key === "completed_range") {
      completedRange = value;
    }
  }
  if (!filter) {
    return { config: null, error: "Invalid Sync Todoist block. Use: filter: today" };
  }
  return {
    config: {
      filter,
      includeCompleted,
      completedBy,
      completedSince,
      completedUntil,
      completedRange
    },
    error: null
  };
}
function buildTaskTree(tasks) {
  var _a, _b;
  const taskMap = /* @__PURE__ */ new Map();
  const childrenMap = /* @__PURE__ */ new Map();
  for (const t of tasks) {
    taskMap.set(t.id, t);
  }
  for (const t of tasks) {
    if (t.parentId && taskMap.has(t.parentId)) {
      const existing = (_a = childrenMap.get(t.parentId)) != null ? _a : [];
      existing.push(t);
      childrenMap.set(t.parentId, existing);
    }
  }
  const roots = [];
  for (const t of tasks) {
    if (!t.parentId || !taskMap.has(t.parentId)) {
      roots.push({
        task: t,
        children: (_b = childrenMap.get(t.id)) != null ? _b : []
      });
    }
  }
  return roots;
}
var PRIORITY_EMOJI = {
  [4 /* HIGH */]: "\u{1F53A}",
  [3 /* MEDIUM */]: "\u23EB",
  [2 /* LOW */]: "\u{1F53C}"
};
function mergeTasks(activeTasks, completedTasks) {
  const tasksById = /* @__PURE__ */ new Map();
  for (const task of [...activeTasks, ...completedTasks]) {
    tasksById.set(task.id, task);
  }
  return Array.from(tasksById.values());
}
function inferCompletedBy(filter) {
  const lower = filter.toLowerCase();
  const hasDateIntent = /\b(today|tomorrow|overdue|date|due|before|after|next|this week|last week)\b/.test(lower);
  const hasProjectOrLabelIntent = /(^|\s)[@#][^\s)]+/.test(filter);
  return hasProjectOrLabelIntent && !hasDateIntent ? "completion_date" : "due_date";
}
function startOfDay(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}
function addDays(date, days) {
  return new Date(date.getTime() + days * DAY_MS);
}
function parseDurationDays(value) {
  const match = value.trim().toLowerCase().match(/^(\d+)\s*([dwm])$/);
  if (!match)
    return null;
  const amount = Number(match[1]);
  const unit = match[2];
  if (unit === "d")
    return amount;
  if (unit === "w")
    return amount * 7;
  return amount * 30;
}
function parseDateBoundary(value, now, boundary) {
  const lower = value.trim().toLowerCase();
  let date = null;
  if (lower === "now") {
    return new Date(now);
  }
  if (lower === "today") {
    date = startOfDay(now);
  } else if (lower === "yesterday") {
    date = addDays(startOfDay(now), -1);
  } else if (lower === "tomorrow") {
    date = addDays(startOfDay(now), 1);
  } else {
    const match = lower.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (match) {
      date = new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]));
    }
  }
  if (!date)
    return null;
  return boundary === "start" ? date : addDays(date, 1);
}
function resolveCompletedRange(value, now) {
  const lower = value.trim().toLowerCase();
  const durationDays = parseDurationDays(lower);
  const until = addDays(startOfDay(now), 1);
  if (durationDays !== null) {
    return { since: addDays(until, -durationDays), until };
  }
  const since = parseDateBoundary(lower, now, "start");
  const rangeUntil = parseDateBoundary(lower, now, "end");
  if (!since || !rangeUntil)
    return null;
  return { since, until: rangeUntil };
}
function resolveCompletedWindow(config, now) {
  var _a, _b, _c;
  const by = (_a = config.completedBy) != null ? _a : inferCompletedBy(config.filter);
  const defaultDays = by === "due_date" ? 42 : 30;
  let since;
  let until;
  if (config.completedRange) {
    const range = resolveCompletedRange(config.completedRange, now);
    if (!range) {
      throw new Error("Invalid completed_range. Use today, yesterday, YYYY-MM-DD, or a duration like 30d/6w.");
    }
    since = range.since;
    until = range.until;
  } else {
    until = config.completedUntil ? (_b = parseDateBoundary(config.completedUntil, now, "end")) != null ? _b : (() => {
      throw new Error("Invalid completed_until. Use today, now, or YYYY-MM-DD.");
    })() : addDays(startOfDay(now), 1);
    if (config.completedSince) {
      const durationDays = parseDurationDays(config.completedSince);
      since = durationDays !== null ? addDays(until, -durationDays) : (_c = parseDateBoundary(config.completedSince, now, "start")) != null ? _c : (() => {
        throw new Error("Invalid completed_since. Use YYYY-MM-DD, today, yesterday, or a duration like 30d/6w.");
      })();
    } else {
      since = addDays(until, -defaultDays);
    }
  }
  if (since >= until) {
    throw new Error("Completed task range must start before it ends.");
  }
  const maxDays = MAX_COMPLETED_WINDOW_DAYS[by];
  const rangeDays = Math.ceil((until.getTime() - since.getTime()) / DAY_MS);
  if (rangeDays > maxDays) {
    const maxLabel = by === "due_date" ? "6w" : "3m";
    throw new Error(`Completed ${by} queries can cover at most ${maxLabel}.`);
  }
  return { by, since, until };
}
function formatDateForLabel(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function renderTaskRow(task, container, plugin, indent) {
  const row = container.createDiv({ cls: `syncist-query-task${indent ? " syncist-query-subtask" : ""}` });
  const checkbox = row.createEl("input", { type: "checkbox", cls: "syncist-query-checkbox" });
  checkbox.checked = task.isCompleted;
  checkbox.addEventListener("change", () => {
    void (async () => {
      try {
        if (checkbox.checked) {
          await plugin.todoistService.completeTask(task.id);
        } else {
          await plugin.todoistService.reopenTask(task.id);
        }
        new import_obsidian5.Notice(checkbox.checked ? `Completed: ${task.content}` : `Reopened: ${task.content}`);
      } catch (err) {
        console.error("Failed to toggle task:", err);
        new import_obsidian5.Notice(`Failed to update task: ${err}`);
        checkbox.checked = !checkbox.checked;
      }
    })();
  });
  const textContainer = row.createDiv({ cls: "syncist-query-task-text" });
  const contentEl = textContainer.createSpan({ cls: "syncist-query-content" });
  const emoji = PRIORITY_EMOJI[task.priority];
  if (emoji) {
    contentEl.createSpan({ text: emoji + " ", cls: "syncist-query-priority" });
  }
  contentEl.createSpan({ text: task.content });
  const metaEl = textContainer.createDiv({ cls: "syncist-query-meta" });
  const badges = [];
  const projectName = plugin.todoistService.getProjectName(task.projectId);
  if (projectName)
    badges.push(`\u{1F4C1} ${projectName}`);
  if (task.due)
    badges.push(`\u{1F4C5} ${task.due.date}`);
  if (task.labels.length)
    badges.push(task.labels.map((l) => `#${l}`).join(" "));
  if (badges.length > 0) {
    metaEl.createSpan({ text: badges.join("  \xB7  "), cls: "syncist-query-badge" });
  }
}
function renderQueryBlock(source, el, plugin) {
  const { config, error } = parseQueryConfig(source);
  if (!config) {
    el.createDiv({ cls: "syncist-query-error", text: error != null ? error : "Invalid Sync Todoist block. Use: filter: today" });
    return;
  }
  if (!plugin.todoistService.isInitialized()) {
    el.createDiv({ cls: "syncist-query-error", text: "Todoist API not configured. Add your token in settings." });
    return;
  }
  const wrapper = el.createDiv({ cls: "syncist-query-block" });
  const header = wrapper.createDiv({ cls: "syncist-query-header" });
  header.createSpan({
    text: config.includeCompleted ? `Filter: ${config.filter} \xB7 including completed` : `Filter: ${config.filter}`,
    cls: "syncist-query-filter-label"
  });
  const refreshBtn = header.createEl("button", { text: "\u21BB", cls: "syncist-query-refresh" });
  refreshBtn.setAttribute("aria-label", "Refresh");
  const listContainer = wrapper.createDiv({ cls: "syncist-query-list" });
  const footerEl = wrapper.createDiv({ cls: "syncist-query-footer" });
  const loadTasks = async () => {
    listContainer.empty();
    footerEl.empty();
    listContainer.createDiv({ cls: "syncist-query-loading", text: "Loading tasks..." });
    try {
      await plugin.todoistService.ensureProjectCache();
      const activeTasks = await plugin.todoistService.getFilteredTasks(config.filter);
      let completedTasks = [];
      let completedWarning = null;
      let completedWindow = null;
      if (config.includeCompleted) {
        try {
          completedWindow = resolveCompletedWindow(config, /* @__PURE__ */ new Date());
          completedTasks = await plugin.todoistService.getCompletedTasks({
            filterQuery: config.filter,
            by: completedWindow.by,
            since: completedWindow.since,
            until: completedWindow.until
          });
        } catch (completedError) {
          completedWarning = completedError instanceof Error ? completedError.message : String(completedError);
          console.warn("Sync Todoist query block completed task lookup failed:", completedError);
        }
      }
      const tasks = mergeTasks(activeTasks, completedTasks);
      listContainer.empty();
      if (tasks.length === 0) {
        listContainer.createDiv({ cls: "syncist-query-empty", text: "No tasks match this filter." });
      } else {
        const tree = buildTaskTree(tasks);
        for (const node of tree) {
          renderTaskRow(node.task, listContainer, plugin, false);
          for (const child of node.children) {
            renderTaskRow(child, listContainer, plugin, true);
          }
        }
      }
      footerEl.createSpan({
        text: `Updated: ${(/* @__PURE__ */ new Date()).toLocaleTimeString()}`,
        cls: "syncist-query-timestamp"
      });
      if (completedWindow) {
        footerEl.createDiv({
          text: `Completed: ${completedWindow.by.replace("_", " ")} ${formatDateForLabel(completedWindow.since)} to ${formatDateForLabel(completedWindow.until)}`,
          cls: "syncist-query-completed-window"
        });
      }
      if (completedWarning) {
        footerEl.createDiv({
          text: `Completed tasks not loaded: ${completedWarning}`,
          cls: "syncist-query-warning"
        });
      }
    } catch (error2) {
      listContainer.empty();
      const message = error2 instanceof Error ? error2.message : String(error2);
      const isFilterError = message.toLowerCase().startsWith("invalid filter");
      if (isFilterError) {
        console.warn("Sync Todoist query block: invalid filter \u2014", message);
      } else {
        console.error("Sync Todoist query block error:", error2);
      }
      listContainer.createDiv({
        cls: "syncist-query-error",
        text: isFilterError ? `${message}. Check the Todoist filter syntax.` : `Failed to load tasks: ${message}`
      });
    }
  };
  refreshBtn.addEventListener("click", () => {
    void loadTasks();
  });
  void loadTasks();
}

// src/main.ts
var TodoistSyncPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.syncIntervalId = null;
    this.statusBarItem = null;
  }
  async onload() {
    console.debug("Loading Sync Todoist plugin...");
    await this.loadSettings();
    await this.loadSyncState();
    this.todoistService = new TodoistService();
    if (this.settings.apiToken) {
      this.todoistService.initialize(this.settings.apiToken);
    }
    this.syncEngine = new SyncEngine(
      this.app,
      this.todoistService,
      this.settings,
      this.syncState
    );
    this.addSettingTab(new TodoistSyncSettingTab(this.app, this));
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar();
    this.registerCommands();
    this.registerMarkdownCodeBlockProcessor("sync-todoist", (source, el) => {
      renderQueryBlock(source, el, this);
    });
    this.registerMarkdownCodeBlockProcessor("syncist", (source, el) => {
      renderQueryBlock(source, el, this);
    });
    this.startSyncInterval();
    console.debug("Sync Todoist plugin loaded");
  }
  onunload() {
    console.debug("Unloading Sync Todoist plugin...");
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
  }
  /**
   * Register plugin commands
   */
  registerCommands() {
    this.addCommand({
      id: "create-todoist-task",
      name: "Create task from current line",
      editorCallback: async (editor, view) => {
        var _a;
        const cursor = editor.getCursor();
        const line = editor.getLine(cursor.line);
        const filePath = (_a = view.file) == null ? void 0 : _a.path;
        if (!filePath) {
          new import_obsidian6.Notice("Cannot determine file path");
          return;
        }
        const result = await this.syncEngine.createTaskFromLine(
          filePath,
          cursor.line,
          line
        );
        new import_obsidian6.Notice(result.message);
        if (result.success) {
          const newContent = await this.app.vault.read(view.file);
          editor.setValue(newContent);
          editor.setCursor(cursor);
          await this.saveSyncState();
        }
      }
    });
    this.addCommand({
      id: "sync-now",
      name: "Sync now",
      callback: async () => {
        if (!this.settings.apiToken) {
          new import_obsidian6.Notice("Please configure your API token in the settings.");
          return;
        }
        if (this.syncEngine.isCurrentlySyncing()) {
          new import_obsidian6.Notice("Sync already in progress, please wait.");
          return;
        }
        new import_obsidian6.Notice("Starting sync...");
        const result = await this.syncNow();
        const message = `Sync complete: ${result.created} created, ${result.updated} updated, ${result.completed} completed`;
        new import_obsidian6.Notice(message);
        if (result.errors.length > 0) {
          new import_obsidian6.Notice(`Sync had ${result.errors.length} error(s). Check console for details.`);
        }
      }
    });
    this.addCommand({
      id: "import-todoist-task",
      name: "Import task from todoist",
      editorCallback: (editor, view) => {
        var _a;
        if (!this.settings.apiToken) {
          new import_obsidian6.Notice("Please configure your API token in the settings.");
          return;
        }
        const filePath = (_a = view.file) == null ? void 0 : _a.path;
        if (!filePath) {
          new import_obsidian6.Notice("Cannot determine file path");
          return;
        }
        const cursor = editor.getCursor();
        new ImportTaskModal(this.app, this.todoistService, (task, subtasks) => {
          void (async () => {
            try {
              const linesInserted = await this.syncEngine.importTaskAtCursor(
                task,
                subtasks,
                filePath,
                cursor.line
              );
              const newContent = await this.app.vault.read(view.file);
              editor.setValue(newContent);
              editor.setCursor({ line: cursor.line + linesInserted, ch: 0 });
              await this.saveSyncState();
              const subtaskMsg = subtasks.length > 0 ? ` (+${subtasks.length} subtask${subtasks.length > 1 ? "s" : ""})` : "";
              new import_obsidian6.Notice(`Imported: ${task.content}${subtaskMsg}`);
            } catch (error) {
              console.error("Failed to import task:", error);
              new import_obsidian6.Notice(`Failed to import task: ${error}`);
            }
          })();
        }).open();
      }
    });
    this.addCommand({
      id: "open-settings",
      name: "Open settings",
      callback: () => {
        const appWithSettings = this.app;
        if (appWithSettings.setting) {
          appWithSettings.setting.open();
          appWithSettings.setting.openTabById("sync-todoist");
        }
      }
    });
  }
  /**
   * Load plugin settings
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * Save plugin settings
   */
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.settings.apiToken) {
      this.todoistService.initialize(this.settings.apiToken);
    }
    if (this.syncEngine) {
      this.syncEngine.updateSettings(this.settings);
    }
  }
  /**
   * Load sync state
   */
  async loadSyncState() {
    var _a;
    const data = await this.loadData();
    this.syncState = (_a = data == null ? void 0 : data.syncState) != null ? _a : { ...DEFAULT_SYNC_STATE };
  }
  /**
   * Save sync state
   */
  async saveSyncState() {
    var _a;
    const data = (_a = await this.loadData()) != null ? _a : {};
    data.syncState = this.syncEngine.getSyncState();
    await this.saveData({ ...this.settings, syncState: data.syncState });
  }
  /**
   * Get current sync state
   */
  getSyncState() {
    var _a, _b;
    return (_b = (_a = this.syncEngine) == null ? void 0 : _a.getSyncState()) != null ? _b : this.syncState;
  }
  /**
   * Perform a sync operation
   */
  async syncNow() {
    this.updateStatusBar("Syncing...");
    try {
      const result = await this.syncEngine.performSync();
      await this.saveSyncState();
      this.updateStatusBar();
      return result;
    } catch (error) {
      this.updateStatusBar("Sync failed");
      throw error;
    }
  }
  /**
   * Start the automatic sync interval
   */
  startSyncInterval() {
    if (this.settings.syncIntervalMinutes <= 0) {
      return;
    }
    const intervalMs = this.settings.syncIntervalMinutes * 60 * 1e3;
    this.syncIntervalId = window.setInterval(() => {
      if (!this.settings.apiToken) {
        return;
      }
      console.debug("Running scheduled sync...");
      void this.syncNow().catch((error) => {
        console.error("Scheduled sync failed:", error);
      });
    }, intervalMs);
    this.registerInterval(this.syncIntervalId);
  }
  /**
   * Restart the sync interval (after settings change)
   */
  restartSyncInterval() {
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
    this.startSyncInterval();
  }
  /**
   * Update the status bar text
   */
  updateStatusBar(text) {
    if (!this.statusBarItem)
      return;
    if (text) {
      this.statusBarItem.setText(`Todoist: ${text}`);
    } else {
      const taskCount = Object.keys(this.getSyncState().tasks).length;
      this.statusBarItem.setText(`Todoist: ${taskCount} tasks`);
    }
  }
};
